name: ci
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: automationcloud/chrome:84
      env:
        CHROME_PATH: /opt/latest/chrome
        CHROME_PORT: "9123"
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Setup npm private token
        run: npm config set '//registry.npmjs.org/:_authToken' '${{ secrets.NPM_TOKEN }}'
      - run: npm run bootstrap
      - run: npm run compile
      - run: npm run lint
      - run: npm test
